### ISSUE TITLE
Plugin makes build fail in non git project

### ISSUE THREAD

**Issue by alcarraz** [jpos/jpos-gradle-plugin#5]
The plugin makes the `jar` task to depend on `createGitRevision` task, that fails if this is not a git repository, the build even fails after performing a `git init` with a `NoHeadException`.

There are many options for this:
1. Not adding the dependency if the project is not in a git repository, and maybe not creating the task at all.
2. Letting a project property select if we want to run the task.
3. Ignore the git exception if a project property is set.
4. All of the above.

The easier to implement are 2 and 3.

I don't know if there is an easy way of asking `jGit` about whether the project is in a git repository or not, without using hard coded literals for implementing 1. But also for this we would need to ask git specific questions from the `JPOSPlugin` class, of course we can relay that to a `GitRevisonTask` method.

**Comment by ar** [comment]
Good point and thank you for PR #6 

I'd like to explore option 1 in order to avoid having to manually set the `ignoreGit` property.

If we go with option 2, it's a good opportunity to use plugin properties so that we can configure something like:

```
jpos {
   ignoreGit = true
}
```
